import Layout from "@/components/Layout";
import { useAuth } from "@/firebase/AuthContext";

import { Poppins } from "next/font/google";
import Head from "next/head";
import { useState } from "react";
import { HiEye, HiEyeOff } from "react-icons/hi";
import { RiChatPrivateFill } from "react-icons/ri";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function AdminLogin() {
  const [showPassword, setShowPassword] = useState(false);
  const [password, setpassword] = useState("");
  const { login, isSignup } = useAuth();
  const handleSubmit = (e) => {
    e.preventDefault();
    if (password) {
      login("info@dhicva.org", password, "/dashboard");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`${poppins.className} bg-green-900 w-full h-screen grid place-items-center`}
      >
        <Layout>
          <ToastContainer />
          <div className="bg-gradient-to-r from-green-50 to-green-300 shadow-sm shadow-gray-700 grid sm:grid-cols-2 mt-14 mb-20  px-8 py-10 rounded-md">
            <div>
              <RiChatPrivateFill className="hidden sm:block  sm:text-[16rem] md:text-[20rem] lg:text-[25rem] text-green-800" />
            </div>
            <div className="container w-full">
              <form onSubmit={handleSubmit}>
                <h1 className="mb-8 text-2xl sm:text-3xl text-center">
                  Admin Login
                </h1>
                <div className="relative">
                  <input
                    type={showPassword ? "text" : "password"}
                    className="block border border-grey-light w-full p-3 rounded mb-1 focus:outline-dotted"
                    placeholder="admin password"
                    onChange={(e) => setpassword(e.target.value)}
                  />

                  <div
                    onClick={() => setShowPassword((prev) => !prev)}
                    className="absolute top-4 md:top-3 right-4 z-99 cursor-pointer"
                  >
                    {showPassword ? (
                      <HiEyeOff className="text-xl md:text-2xl" />
                    ) : (
                      <HiEye className="text-xl md:text-2xl" />
                    )}
                  </div>
                </div>

                <button
                  type="submit"
                  className="w-full text-center py-3 rounded bg-green-500 shadow-sm shadow-black  my-1 font-medium uppercase"
                >
                  {isSignup ? (
                    <>
                      Loggin
                      <div className="w-5 h-5 rounded-full border-r-2 border-l-2 border-green-900 animate-spin inline-block ml-2 "></div>
                    </>
                  ) : (
                    "login"
                  )}
                </button>
              </form>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
