import Button from "@/components/Button";
import HeadLine from "@/components/HeadLine";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import TopNavbar from "@/components/TopNavbar";
import Footer from "@/components/sections/Footer";
import { Poppins } from "next/font/google";
import Head from "next/head";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <TopNavbar />
      <Navbar />

      <main className={`${poppins.className} mt-14 mb-10`}>
        <Layout>
          <div className="grid md:grid-cols-2 gap-x-4 ">
            <img
              className="rounded-lg w-full h-full mb-8  md:mb-0 order-2 md:order-1 mt-10 md:mt-0 "
              src="/images/about_mosque.png"
              alt="about"
            />
            <div className="order-1 md:order-2">
              <HeadLine tittle="about dhic" />
              <p className="text-lg my-4">
                Darul Hikmah Islamic Center (DHIC) is an independent,
                non-profit, community-based, religious 501(c)(3) organization.
                DHIC provides a dynamic space that cultivates an exchange of
                ideas about Islam through culture, charity, and education
                programs. The DHIC is not just a mosque for prayers rather it is
                a community center for all. The Center is committed to
                preserving an Islamic identity, building and supporting a viable
                Muslim community, promoting a comprehensive Islamic way of life
                based on the Holy Quran and the Sunnah of Prophet Muhammad.
              </p>
              <Button name="read more" />
            </div>
          </div>
          <div className="mt-24">
            <div className="grid md:grid-cols-2 items-center bg-green-800/20 px-5 md:pl-8 md:pr-0 rounded-md">
              <div className="pt-14">
                <h1 className="text-2xl font-bold mb-6">
                  Prophet Muhammad (saw) said-
                </h1>
                <p className="text-lg text-gray-800">
                  “Make things easy for people and not difficult. Give people
                  good news and bring them joy, and do not turn them away.”
                </p>
              </div>
              <div>
                <img
                  className="max-w-[300px] mx-auto"
                  src="/images/quran.png"
                  alt="s"
                />
              </div>
            </div>
          </div>
        </Layout>
      </main>
      <Footer />
    </>
  );
}
