import Navbar from "@/components/Navbar";
import Footer from "@/components/sections/Footer";
import { Poppins } from "next/font/google";
import Head from "next/head";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={poppins.className}>
        <Navbar />
      </header>
      <main className={`${poppins.className} md:mx-16 mx-4`}>
        <p>about us</p>
      </main>
      <Footer />
    </>
  );
}
