import HeadLine from "@/components/HeadLine";
import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import { firestoreDb } from "@/firebase";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function About() {
  const [announcement, setAnnouncement] = useState({});
  const collectionRef = collection(firestoreDb, "status");

  //fetch announcement function
  const fetchData = async () => {
    const q = query(collectionRef, orderBy("date", "desc"));
    const snapshot = await getDocs(q);
    setAnnouncement({ ...snapshot.docs[0].data(), id: snapshot.docs[0].id });
  };
  useEffect(() => {
    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Announcement</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={poppins.className}>
        <Navbar />
      </header>
      <main className={`${poppins.className} md:mx-16 mx-4`}>
        <Layout className="mt-14 mx-10">
          <HeadLine tittle="announcement" />
          <div
            className="text-xl mb-4 capitalize"
            dangerouslySetInnerHTML={{
              __html: announcement
                ? announcement.info
                : "there is no announcements",
            }}
          />
        </Layout>
      </main>
    </>
  );
}
