import Navbar from "@/components/Navbar";
import Announcement from "@/components/sections/Announcement";
import Banner from "@/components/sections/Banner";
import Donate from "@/components/sections/Donate";
import Footer from "@/components/sections/Footer";
import Hero from "@/components/sections/Hero";
import KnowIslam from "@/components/sections/KnowIslam";
import OurWork from "@/components/sections/OurWork";
import Philosophy from "@/components/sections/Philosophy";
import PrayerTime from "@/components/sections/PrayerTime";
import RecentNews from "@/components/sections/RecentNews";
import TopNavbar from "@/components/TopNavbar";
import { Inter, Poppins } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>mosque</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <TopNavbar />
      <Navbar />
      <main className={`${poppins.className}`}>
        <Hero />
        <PrayerTime />
        <KnowIslam />
        <Announcement />
        <RecentNews />
        <Banner />
        <OurWork />
        <Donate />
        <Philosophy />
      </main>
      <Footer />
    </>
  );
}
