import Navbar from "@/components/Navbar";
import Footer from "@/components/sections/Footer";
import Hero from "@/components/sections/Hero";
import Philosophy from "@/components/sections/Philosophy";
import PrayerTime from "@/components/sections/PrayerTime";
import TopNavbar from "@/components/TopNavbar";
import { Inter, Poppins } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavbar />
      <Navbar />
      <main className={`${poppins.className} max-w-[1450px] mx-auto`}>
        <Hero />
        <PrayerTime />
        <Philosophy />
        <Footer />
      </main>
    </>
  );
}
