import Navbar from "@/components/Navbar";
import TopNavbar from "@/components/TopNavbar";
import Footer from "@/components/sections/Footer";
import PrayerTime from "@/components/sections/PrayerTime";
import { Poppins } from "next/font/google";
import Head from "next/head";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function Prayertime() {
  return (
    <>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <TopNavbar />
      <Navbar />

      <main className={`${poppins.className} mb-14`}>
        <PrayerTime />
      </main>
      <Footer />
    </>
  );
}
