import Navbar from "@/components/Navbar";
import axios from "axios";
import { Inter, Poppins } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function Prayer() {
  const [prayerTime, setPrayerTime] = useState({});

  const getPrayerTime = async (city) => {
    const { data } = await axios.get(
      `https://dailyprayer.abdulrcs.repl.co/api/${city}`
    );
    setPrayerTime(data.today);
    console.log(data.today);
  };

  useEffect(() => {
    getPrayerTime("virginia");
  }, []);
  const linkClass =
    "lg:mr-9 uppercase font-medium text-gray-700 text-md hover:text-gray-900 block lg:inline ";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={poppins.className}>
        <Navbar />
      </header>
      <main className={`${poppins.className} md:mx-16 mx-4`}>
        <section className="">
          <div className="flex justify-between my-8">
            <h3 className="capitalize text-2xl font-bold">prayer timing</h3>
            <select
              onChange={(e) => getPrayerTime(e.target.value)}
              className="bg-orange-400 px-2 py-2 capitalize text-white rounded-md font-medium"
            >
              <option value="virginia">Virginia</option>
              <option value="newyork">New York</option>
              <option value="dhaka">Dhaka</option>
            </select>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-8 gap-y-8">
            <div>
              <h3 className="text-3xl font-bold capitalize ">
                Weslcome To the Darul Hikmah Islamic Center
              </h3>
              <p className="my-4">
                Darul Hikmah Islamic Center (DHIC) is an independent,
                non-profit, community-based, religious 501(c)(3) organization.
                DHIC provides a dynamic space that cultivates an exchange of
                ideas about Islam through culture, charity, and education
                programs. The DHIC is not just a mosque for prayers rather it is
                a community center for all. The Center is committed to
                preserving an Islamic identity, building and supporting a viable
                Muslim community, promoting a comprehensive Islamic way of life
                based on the Holy Quran and the Sunnah of Prophet Muhammad.
              </p>
              <button className="bg-orange-400 py-1 px-4 text-white uppercase font-medium rounded-md hover:bg-orange-500 block ">
                read more
              </button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
