import Navbar from "@/components/Navbar";
import Footer from "@/components/sections/Footer";

import TopNavbar from "@/components/TopNavbar";
import { Inter, Poppins } from "next/font/google";
import Head from "next/head";
// Import Swiper React components

// Import Swiper styles
import Layout from "@/components/Layout";
import React from "react";
import "swiper/css";
import "swiper/css/navigation";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export default function Home() {
  const containerRef = React.useRef(null);
  const itemHeight = 100; // Change this to the actual height of each item

  function scrollUp() {
    containerRef.current.scrollTo({
      top: containerRef.current.scrollTop - itemHeight,
      behavior: "smooth",
    });
  }

  function scrollDown() {
    containerRef.current.scrollTo({
      top: containerRef.current.scrollTop + itemHeight,
      behavior: "smooth",
    });
  }
  const imageUrl =
    "https://images.unsplash.com/photo-1680176750034-8d11a2f71096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1032&q=80";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavbar />
      <Navbar />
      <main className={`${poppins.className} max-w-[1450px] mx-auto`}>
        <Layout className="mt-16">
          <h2 className="text-4xl text-center font-bold capitalize  mb-4">
            recent news and update
          </h2>
          <p className="mx-auto text-center mt-3 w-[90%] sm:w-[50%] ">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto eum
            quo pariatur sapiente magni voluptatem?
          </p>

          <div className="grid md:grid-cols-2 gap-x-5 mt-8 mx-2 md:mx-0">
            <div className="mb-8 md:mb-0">
              <img className="rounded-lg mb-2" src={imageUrl} alt="fg" />
              <small className="text-green-800 capitalize">april 04,2023</small>
              <h3 className="font-medium capitalize text-lg text-gray-900 my-1">
                a miracle of the quran mother's milk
              </h3>
              <p className="text-gray-800">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Possimus, esse odit incidunt laudantium blanditiis corporis illo
                ipsum eaque porro reprehenderit.
              </p>
              <button className="underline capitalize font-medium mt-2 text-gray-800">
                read more
              </button>
            </div>
            <div>
              <div className="slider-container" ref={containerRef}>
                <div className="slider-wrapper">
                  <div className="slider-item">Item 1</div>
                  <div className="slider-item">Item 2</div>
                  <div className="slider-item">Item 3</div>
                  <div className="slider-item">Item 4</div>
                  <div className="slider-item">Item 5</div>
                  <div className="slider-item">Item 6</div>
                  ...
                </div>
                <button onClick={scrollUp}>Up</button>
                <button onClick={scrollDown}>down</button>
              </div>
            </div>
          </div>
        </Layout>
      </main>
      <Footer />
    </>
  );
}
