import Navbar from "@/components/dashboard/Navbar";
import SideNavbar from "@/components/dashboard/SideNavbar";
import { firestoreDb } from "@/firebase";
import { Timestamp, addDoc, collection } from "firebase/firestore";
import dynamic from "next/dynamic";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { useState } from "react";
import "react-quill/dist/quill.snow.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });
const ReactQuill = dynamic(() => import("react-quill"), {
  ssr: false,
});

function Announcement() {
  const [value, setValue] = useState("");
  const [loading, setLoading] = useState(false);
  const collectionRef = collection(firestoreDb, "status");
  const handleSubmit = async () => {
    setLoading(true);
    const resdata = await addDoc(collectionRef, {
      info: value,
      date: Timestamp.now(),
    });
    setLoading(false);
    toast.success("Uploaded successfuly", { autoClose: 1000 });
  };
  return (
    <>
      <Head>
        <title>Announcement</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main
        className={`${poppins.className} bg-gray-800 font-sans leading-normal tracking-normal mt-12`}
      >
        <ToastContainer />
        <div className="flex flex-col md:flex-row">
          <SideNavbar />
          <section className="bg-white p-6 w-full">
            <ReactQuill theme="snow" value={value} onChange={setValue} />
            <button
              className="bg-green-600 py-1 px-4 text-white uppercase font-medium rounded-md hover:bg-lime-600 mt-2 ml-auto block"
              onClick={handleSubmit}
            >
              {loading ? (
                <>
                  Submiting
                  <div className="w-5 h-5 rounded-full border-r-2 border-l-2 border-green-900 animate-spin inline-block ml-2 "></div>
                </>
              ) : (
                "Submit"
              )}
            </button>
          </section>
        </div>
      </main>
    </>
  );
}

export default Announcement;
