import Navbar from "@/components/dashboard/Navbar";
import SideNavbar from "@/components/dashboard/SideNavbar";
import { Poppins } from "next/font/google";
import Head from "next/head";
const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

function Prayertime() {
  return (
    <>
      <Head>
        <title>prayer time</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main
        className={`${poppins.className} bg-gray-800 font-sans leading-normal tracking-normal mt-12`}
      >
        <div className="flex flex-col md:flex-row">
          <SideNavbar />
          <section className="bg-white p-6 w-full">
            <h1>prayer</h1>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Voluptatum consequatur id corporis voluptas officia nemo aliquam,
              provident tempore placeat atque ducimus fugiat quia nostrum labore
              consectetur repudiandae saepe earum quasi vero animi. Omnis, amet
              veritatis. Odit iusto dolorum ex, alias sit voluptate, modi
              reiciendis incidunt minima soluta hic sunt itaque.
            </p>
          </section>
        </div>
      </main>
    </>
  );
}

export default Prayertime;
