import HeadLine from "@/components/HeadLine";
import Layout from "@/components/Layout";
import Navbar from "@/components/dashboard/Navbar";
import SideNavbar from "@/components/dashboard/SideNavbar";
import { firestoreDb } from "@/firebase";
import {
  Timestamp,
  addDoc,
  collection,
  doc,
  getDocs,
  setDoc,
} from "firebase/firestore";
import { Poppins } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
import { ToastContainer, toast } from "react-toastify";
const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

function Prayertime() {
  const [loading, setLoading] = useState(false);
  const prayerName = {
    fajr: "05:35 AM",
    dhuhr: "01:02 PM",
    asr: "04:48 PM",
    maghrib: "07:34 PM",
    isha: "08:50 PM",
    jummah: "01:00 PM",
  };
  const [prayer, setPrayer] = useState(prayerName);
  const collectionRef = collection(firestoreDb, "prayers");

  const handleChange = (e) => {
    let { name, value } = e.target;
    setPrayer({ ...prayer, [name]: value });
  };

  const handleSubmit = async () => {
    setLoading(true);
    const snapshot = await getDocs(collectionRef);
    if (snapshot.empty) {
      const resData = await addDoc(collectionRef, {
        prayer_time: prayer,
        date: Timestamp.now(),
      });
      setLoading(false);
      toast.success("Uploaded successfuly", { autoClose: 1000 });
    } else {
      const docId = snapshot.docs[0].id;
      await setDoc(doc(firestoreDb, "prayers", docId), prayer);
      setLoading(false);
      toast.success("Updated successfuly", { autoClose: 1000 });
    }
  };

  useEffect(() => {}, []);

  return (
    <>
      <Head>
        <title>prayer time</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <main
        className={`${poppins.className} bg-gray-800 font-sans leading-normal tracking-normal mt-12`}
      >
        <div className="flex flex-col md:flex-row">
          <ToastContainer />
          <SideNavbar />
          <section className="bg-white p-6 w-full">
            <Layout className="mt-16">
              <HeadLine tittle="prayer time update" />
              <form className="grid grid-cols-3 gap-4">
                <div className="relative">
                  <label className="prayer_label" htmlFor="fajr">
                    Fajr
                  </label>
                  <input
                    type="text"
                    name="fajr"
                    className="prayer_input"
                    placeholder="fajr"
                    value={prayer.fajr}
                    onChange={handleChange}
                  />
                </div>
                <div className="relative">
                  <label className="prayer_label" htmlFor="dhuhr">
                    Dhuhr
                  </label>
                  <input
                    type="text"
                    name="dhuhr"
                    className="prayer_input"
                    placeholder="dhuhr"
                    value={prayer.dhuhr}
                    onChange={handleChange}
                  />
                </div>
                <div className="relative">
                  <label className="prayer_label" htmlFor="asr">
                    Asr
                  </label>
                  <input
                    type="text"
                    name="asr"
                    className="prayer_input"
                    placeholder="asr"
                    value={prayer.asr}
                    onChange={handleChange}
                  />
                </div>
                <div className="relative">
                  <label className="prayer_label" htmlFor="maghrib">
                    Maghrib
                  </label>
                  <input
                    type="text"
                    name="maghrib"
                    className="prayer_input"
                    placeholder="maghrib"
                    value={prayer.maghrib}
                    onChange={handleChange}
                  />
                </div>
                <div className="relative">
                  <label className="prayer_label" htmlFor="isha">
                    isha's
                  </label>
                  <input
                    type="text"
                    name="isha"
                    className="prayer_input"
                    placeholder="isha's"
                    value={prayer.isha}
                    onChange={handleChange}
                  />
                </div>
                <div className="relative">
                  <label className="prayer_label" htmlFor="jummah">
                    Jummah
                  </label>
                  <input
                    type="text"
                    name="jummah"
                    className="prayer_input"
                    placeholder="jummah"
                    value={prayer.jummah}
                    onChange={handleChange}
                  />
                </div>
              </form>
              <button
                className="bg-green-600 py-1 px-4 text-white uppercase font-medium rounded-md hover:bg-lime-600 mt-2 ml-auto block"
                onClick={handleSubmit}
              >
                {loading ? (
                  <>
                    Submiting
                    <div className="w-5 h-5 rounded-full border-r-2 border-l-2 border-green-900 animate-spin inline-block ml-2 "></div>
                  </>
                ) : (
                  "Submit"
                )}
              </button>
            </Layout>
          </section>
        </div>
      </main>
    </>
  );
}

export default Prayertime;
